version: "3.2"
services:
  db:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-database-dev
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 127.0.0.1:27017:27017
  backend:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-backend-dev
    depends_on:
      - db
    restart: on-failure
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - type: bind
        source: .
        target: /code
